behaviors: 
  Brake: 
    hyperparameters: 
      batch_size: 128
      beta: 0.01
      buffer_size: 1024
      epsilon: 0.25
      lambd: 0.95
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 4
    keep_checkpoints: 5
    max_steps: 1000000
    network_settings: 
      hidden_units: 32
      normalize: false
      num_layers: 1
    reward_signals: 
      extrinsic: 
        gamma: 0.99
        strength: 1.0
    summary_freq: 5000
    time_horizon: 64
    trainer_type: ppo
