behaviors: 
  Brake: 
    hyperparameters: 
      batch_size: 128
      beta: 0.005
      beta_schedule: constant
      buffer_size: 2048
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 3
    max_steps: 1000000
    network_settings: 
      hidden_units: 128
      normalize: false
      num_layers: 2
    reward_signals: 
      extrinsic: 
        gamma: 0.99
        strength: 1.0
    summary_freq: 1000
    keep_checkpoints: 5
    time_horizon: 128
    trainer_type: ppo